ALTER TYPE "ModePaiement" ADD VALUE IF NOT EXISTS 'ESPECES';
ALTER TYPE "ModePaiement" ADD VALUE IF NOT EXISTS 'ASSURANCE';

CREATE TYPE "ModeFacture" AS ENUM ('CASH', 'AVANCE', 'SOLDE', 'PRISE_EN_CHARGE', 'ABONNE', 'CONVENTIONNE');
CREATE TYPE "TypeFacture" AS ENUM ('STANDARD', 'GROS');

ALTER TABLE "commandes" ADD COLUMN "mode_facture" "ModeFacture" NOT NULL DEFAULT 'CASH';
ALTER TABLE "commandes" ADD COLUMN "type_facture" "TypeFacture" NOT NULL DEFAULT 'STANDARD';
ALTER TABLE "commandes" ADD COLUMN "remise" DECIMAL(12, 2) NOT NULL DEFAULT 0;
ALTER TABLE "commandes" ADD COLUMN "frais_divers" DECIMAL(12, 2) NOT NULL DEFAULT 0;
ALTER TABLE "commandes" ADD COLUMN "numero_recu" TEXT;
ALTER TABLE "commandes" ADD COLUMN "monnaie" TEXT NOT NULL DEFAULT 'USD';
